Team254/cheesy-arena

db/migrations/20150324201112_AddFRCEventsAPIColumns.sql
db/migrations/20150401132914_AddTBAColumns.sql
event_settings.go
event_settings_test.go
reports.go
setup_settings.go
setup_teams.go
tba.go
templates/setup_settings.html
templates/setup_teams.html

I changed the code base to use the FRC Events API to pull down team info.  The existing method is non-functional right now due to FIRST having pulled down the page it scrapes causing an exception to be thrown until the feature is disabled.
Using the FRC Events API works well but has a few disadvantages:
* End-users must obtain and API Key
* It is difficult to get all the team information at once because the API will only return 20 teams at a time.  This requires that we make a request for each team.
I added 3 new fields to the event settings table:
* FMSAPIDownloadEnabled (whether to use the API or not)
* FMSAPIUsername (the username to use for authentication)
* FMSAPIAuthKey (the authentication key to use for authentication)
They were added in a new migration to preserve existing …

Use FRC Events API for team info

---

.travis.yml

Default Travis CI behavior is to fetch all dependencies including test
dependencies, then build, and test, which should be sufficient.
These builds will fail till the unit tests are fixed (which I'll probably put in a different PR)

Add basic travis CI YAML

---

templates/match_play.html

With `type="text"` on the Match Play display, team numbers could be any string. There's no reason a team number should ever be anything besides an integer, and non-numeric characters get stripped, anyways.

Force numeric team number

---

driver_station_connection.go

The 2 bytes should be reporting the time left in the current period, not
the time total left in the match.

Fixes autonomous reported time to driver station

---

setup_schedule.go
templates/setup_schedule.html
web.go

Co-written by @ograff 
Adds a button to the match schedule generation to force a push to TBA - useful for when you want to generate and save a match schedule before publishing it to everyone. The frontend code was based off of the similar button to force publish the team list to TBA.

Allow force publishing of the schedule (fixes #24)

---

static/css/cheesy-arena.css

This fixes [the issue noted on #19](https://github.com/Team254/cheesy-arena/pull/19#issuecomment-252406733). It will remove the annoying chromium `up` and `down` number input buttons, which are useless when team numbers are in the thousands.

Remove number input spinners

---

driver_station_connection.go

So it includes timestamps in the console output.

Switch DS dropouts to use `log`

---

README.md
TODO.md

I literally did nothing except fix the title formatting in the readme/todo files because some update to Markdown broke it or something (TBA had the same issue).

Fixed title formatting in markdown

---

driver_station_connection.go

This lets it control driver stations without prompting to allow taking
control.

Change the UDP port number to the one FMS uses

---

field/bandwidth_monitor.go
field/team_match_log.go
templates/fta_display.html
templates/match_play.html

Two small changes in one PR. Didn't feel like two separates were necessary.
Change 1: swap units of bandwidth measurement to megabits per second from megabytes per second. Robots will never come anywhere close to transmitting data amounting to actual megabytes, so megabits allows for field staff to quantify data transmission and also is what's used by the official field.
Change 2: the columns on match logs were shifted because of the addition of logging the radio connection state independent of the Rio. Now the columns are formatted correctly for each data field.
Both these changes were tested this past weekend at Capital City Classic without issue.

Change bandwidth units to megabits + fix .csv match log formatting

---

templates/setup_settings.html
web/setup_settings.go

It was a little annoying that the event name input box in the settings did not clear itself when it was clicked on.
This pull request fixes that and stops the user from accidentally clearing the event name while changing other settings

Change event name in settings from a preset value to a placeholder

---

switch_config.txt

What: First block of ports on the switch are now reserved for special use and have been made trunks.
Port 47 and 48 as well as the SFP ports are also trunks.
Why: Spare trunk ports to accommodate for future field network gear

Added more Trunk ports to accommodate for future field network gear

---

field/arena.go
model/event_settings.go
network/access_point.go
network/access_point_test.go
templates/setup_settings.html
web/setup_settings.go

This commit adds a configuration setting that will commit team network configurations to the AP one at a time instead of all in one message. This is how FIRST FMS configures the AP, it seems to be more reliable due to a bug in OpenWRT when you commit the entire config at once.
I have left this as a setting since I'm not confident in this being reliable enough to be the default mode. It will be run in this mode at CalGames, and after some events have used it, I will be confident in setting this to be the default, and eventually making it the only mode.
The slow down is to ~15s to configure the AP, but I feel that this is worth it to not have errors updating the configuration that delay match play.
Let me know what you think

Add mode for setting AP networks slowly

---

field/arena.go

Fixes edge case where the PLC triggers the buzzer during a match.

Disable PLC buzzer during auto and teleop

---

static/js/match_play.js
templates/match_play.html

Allows manually toggle Field Reset on the Alliance Station Displays.
This option is disabled during Auto and Teleop.

Add Field Reset to Alliance Display switcher

---

field/arena.go

Continue to count Cargo for 5 Seconds after the match ends per 2022 Game Manual.
Co-Authored-By: Ed Jordan <ed@ed-jordan.com>

Count Cargo for 5 Seconds Post Match

---

static/css/field_monitor_display.css
static/js/field_monitor_display.js
templates/base.html
templates/field_monitor_display.html
web/field_monitor_display.go
web/field_monitor_display_test.go

Add configuration for field monitor to only show one alliance and blank out during matches. 
Allows for a wired field monitor in each driver station.

Driver Station Field Monitor

---

static/css/view_match_log.css
templates/base.html
templates/match_logs.html
templates/view_match_log.html
web/match_logs.go
web/web.go

This change adds a basic viewer to the data that is logged into the match log files.  It is the start of work for issue https://github.com/Team254/cheesy-arena/issues/119 and more features are planned, but as this is my first contribution I wanted to make sure I put this forward for review if there are issues with my approach.
Things I have on my roadmap for the feature:
- Elevator buttons to move to next/previous connection/disconnection event in the log
- Tracking the time an indicator is in a bad state (similar to the count up timer in the match play screen)
- Adding match graphs for individual team logs
- Adding match graphs that will show multiple teams to look for field wide issues

Added match log viewing

---

network/switch.go
network/switch_test.go
switch_config.txt

Updated DHCP ranges to match FIRST FMS config
https://docs.wpilib.org/en/stable/docs/networking/networking-introduction/networking-basics.html#ethernet-wireless
Team DHCP range is now 10.TE.AM.20 - 10.TE.AM.199
VLAN100 DHCP range is now 10.0.100.126 - 10.0.100.199, 10.0.100.226 - 10.0.100.254

Update DHCP Ranges

---

static/js/match_play.js
templates/match_play.html

disabled additional buttons as suggested here https://github.com/Team254/cheesy-arena/issues/178

Disable video switcher buttons when match play buttons are disabled

---

field/arena.go
field/arena_notifiers.go
model/event_settings.go
static/css/audience_display.css
static/js/audience_display.js
templates/audience_display.html
templates/setup_settings.html
web/alliance_selection.go
web/setup_settings.go

This is another attempt at what @legoktm worked on several years back.
I'm using 3 columns instead of 4 so I'm hoping that gets rid of the overlap issues.
If not let me know what resolution I need to test on and I'll fix it.

Adds the option to show unpicked teams during alliance selection

---

templates/view_match_log.html

Additional work on #119. This adds plots to the individual team match logs.

Adds plots to log viewer

---

field/test_helpers.go
model/test_helpers.go

The test helpers are currently using a unix-only pattern for creating temporary databases which fail when running tests on windows. Windows doesn't allow unlinking an open file, so in the current code the os.Remove silently fails on windows and leaves a database file around causing all tests that create a new database to see an existing non-writable db file and fail.
This PR switches to using Go's native solution for temporary files in tests, which cleanly removes the directory at the end of the test on all platforms.
There's a deeper change that could be done here of also removing the uniqueName argument from all of the tests since it's not needed any more, let me know if you'd like me to also do that.
These changes get the pass rate on windows up to ~97%. There's some other failures …

Make the test harnesses compatible with windows

---

switch_config.txt

This change to the config is working for my Catalyst 3560G series switch to allow for internet uplink from VLAN 100 only.
This does require an external router on the same VLAN to be plugged into one of the VLAN 100 ports (such as 7 indicated here https://github.com/Team254/cheesy-arena/wiki/Field-Network-Setup).
Changing the default gateway to `10.0.100.3` fixed an issue I had with my mac not being able to cross VLANs to talk to the driver stations, and then adding the ip route from `0.0.0.0` to `10.0.100.1` tells the router in the switch that if it can't resolve the IP to something local that it should forward the traffic off to that IP which should be statically set on the external router
This fix should allow you to remove the comment here: …

Update switch config to allow for internet uplink

---

static/css/scoring_panel.css
static/js/scoring_panel.js
templates/scoring_panel.html

Swap the layout of the L1 coral counter to put the auto count in large numbers when inputting autonomous scores.

Make L1 coral count clearer when editing auto

---

static/css/alliance_station_display.css
templates/alliance_station_display.html
templates/match_play.html
web/match_play.go
web/referee_panel.go

For systems that don't use the Cypress Team Signs these updates add the Purple "Count" display on the Alliance Station Signs.

Add Count Mode to Alliance Station Displays

---

web/api.go

CORS headers are missing from API endpoints, which prevents fetch()-ing data. This is necessary for third-party tools, such as the FIRST Game Announcer tool, to read data from the Cheesy Arena server.

Adding CORS to API endpoints

---

static/css/cheesy-arena.css
templates/setup_settings.html

Simple stylizing to make the place holder text a bit more obvious, they either need to be set or are not set #240

Add red italic placeholder styles for input fields in the form

---

field/arena.go
game/foul.go
game/score_test.go
game/test_helpers.go
web/match_play_test.go
web/referee_panel.go
web/scoring_panel.go

Add a unique ID field to the foul structure to enable tracking modifications to fouls.
The main goal of this is to allow external VAR tooling to record fouls being entered and recognize edits/deletions made by the head ref, but it generalizes to anything else connected to realtime score data (eg this could be extended to allow scorer panels to identify which fouls are theirs and provide a remove foul button). Without this, complex heuristics are needed to identify which foul was edited or removed when a change is made.
There's a follow-up change that may be useful of changing the referee panels to edit fouls based on this ID, rather than on list index. Currently there are race conditions where adjustments to the foul list can change which foul is modified by a websocket request, since …

Add a unique ID field to fouls
